<a href="https://colab.research.google.com/github/FelixBuk/tod-Colab/blob/main/%D0%A1%D0%B5%D0%BC%D0%B8%D0%BD%D0%B0%D1%80_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.Создать в numpy матрицу 11 на 7 вида: [[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]

In [ ]:
import numpy as np
a1 = np.array([range(i, i + 7) for i in [v for v in range(1, 102, 10)]])
print(a1)

[[  1   2   3   4   5   6   7]
 [ 11  12  13  14  15  16  17]
 [ 21  22  23  24  25  26  27]
 [ 31  32  33  34  35  36  37]
 [ 41  42  43  44  45  46  47]
 [ 51  52  53  54  55  56  57]
 [ 61  62  63  64  65  66  67]
 [ 71  72  73  74  75  76  77]
 [ 81  82  83  84  85  86  87]
 [ 91  92  93  94  95  96  97]
 [101 102 103 104 105 106 107]]


2.Средствами numpy рассчитать произведения четных чисел от 2 до 20 на ближайшие к ним бОльшие нечетные числа.

In [ ]:
print(np.arange(2, 21, 2)+np.arange(3, 22, 2))

[ 5  9 13 17 21 25 29 33 37 41]


3.Создать две матрицы 30 на 3 из случайных целых чисел из диапазона от 0 до 10 и найти все значения первой матрицы, которые больше соответсвующих (по расположению) значений второй матрицы. Подсчитать сумму этих значений.

In [ ]:
a3 = np.random.randint(0, 10, (3, 3))
b3 = np.random.randint(0, 10, (3, 3))
print(a3)
print(b3)
print(a3[a3>b3].sum())

[[2 4 2]
 [0 7 6]
 [3 4 6]]
[[5 5 5]
 [8 2 3]
 [7 9 7]]
13


4.Написать функцию, которая для целых значений n и m будет возвращать матрицу размера n на m, заполненную текстурой размера 2 на 2 состоящей из следующий значений:
0 1

2 3
Пример для n=5 и m = 4:

0 1 0 1 0

2 3 2 3 2

0 1 0 1 0

2 3 2 3 2

In [ ]:
n, m = int(input('Введите значение n: ')), int(input('Введите значение m: '))
a4 = np.array([[0, 1], [2, 3]])
print(np.tile(a4, (n, m))[:m, :n])

Введите значение n: 5
Введите значение m: 4
[[0 1 0 1 0]
 [2 3 2 3 2]
 [0 1 0 1 0]
 [2 3 2 3 2]]


5.При помощи прихотливого индексирования для двухмерного массива размерности (20, 20), состоящего из случайных целых чисел в пределах от 0 до 10 получить массив элементов находящихся на диагонали, проходящей над основной диагональю.


In [ ]:
a5 = np.random.randint(0, 11, (20, 20))
print(a5)
ind2 = np.arange(1, 20)
ind1 = np.arange(19)
print('Массив элементов находящихся на диагонали, проходящей над основной диагональю: ',a5[ind1, ind2])

[[10  5  2  5  2  6  8  3  8  3  2  3  4  0  9  0  0  0 10  1]
 [ 5  3  4  4  7  0  7  0  5  2  0  7  1  2  4  2  4  8  8  8]
 [ 3  0  0  2 10  6  8  3  7  2 10  5  7  7  5 10  5  5  7  4]
 [ 8  0  1  1 10  9  9  4  4  0  5  2  0  9  2  5  7  7  0 10]
 [10  6  4  1 10  5  3  0  3  8  2  5 10  3  6  6  0  2  3  4]
 [10  1  6  6  7  3  6  1  7  1  3  6  8  3 10  8  0  6  1  2]
 [ 5 10  1  3  8  2  4  2  1  7  7 10  0  4  4  7  6  8  8  4]
 [ 1  8  4  8  9  1  1  5  3  0  6  9  2  9  6  9  3  5  3  1]
 [ 5  2  9  7  7  0  3  7  7  5  9  7  4  8  3  5  7  4  9  5]
 [ 4  3 10  9  0  0  2  1  7  1  0  8 10  5  6  0  5  7  2  8]
 [ 3  3  1  5  2 10  9  5 10 10  3 10  9  2  2  4  5  5  4  1]
 [ 3  1  1  1  4  6  1  3  1  6  3  9  4  8  0  9  4  1  6 10]
 [ 4  0  4  9  7  4  1  7  0  3  1  6  1 10  6  1  0  3  4  2]
 [ 0  8  5  9  0  5  7 10  1  1  5  8  7  2  2  1  9  2  3 10]
 [ 9  9  8  1  5  6  7  2  2  1  9  1  6  8  7  0  1  8  8  3]
 [ 2  8  5  9  8 10  7  1  9  3  0  0  6  2  3  4  5  7

6.Имеется массив из 10 названий городов. При помощи прихотливой индексации сгенерировать последовательность из 100 элементов представляющих случайный выбор из названий городов.

In [ ]:
a6 = np.array(['Москва', 'Лондон', 'Нью-Йорк', 'Токио', 'Барселона', 'Париж', 'Берлин', 'Пекин', 'Вашингтон', 'Минск'])
ind = np.random.randint(0, 10, (1, 100))
print(a6[ind])

[['Нью-Йорк' 'Токио' 'Вашингтон' 'Минск' 'Лондон' 'Вашингтон' 'Берлин'
  'Пекин' 'Берлин' 'Вашингтон' 'Париж' 'Барселона' 'Париж' 'Нью-Йорк'
  'Берлин' 'Токио' 'Лондон' 'Лондон' 'Берлин' 'Пекин' 'Барселона'
  'Берлин' 'Пекин' 'Лондон' 'Барселона' 'Вашингтон' 'Барселона' 'Пекин'
  'Париж' 'Токио' 'Вашингтон' 'Москва' 'Лондон' 'Париж' 'Берлин' 'Лондон'
  'Пекин' 'Минск' 'Пекин' 'Нью-Йорк' 'Москва' 'Берлин' 'Минск' 'Нью-Йорк'
  'Лондон' 'Париж' 'Лондон' 'Вашингтон' 'Париж' 'Барселона' 'Вашингтон'
  'Вашингтон' 'Берлин' 'Москва' 'Вашингтон' 'Нью-Йорк' 'Нью-Йорк'
  'Вашингтон' 'Пекин' 'Пекин' 'Лондон' 'Москва' 'Токио' 'Пекин' 'Токио'
  'Токио' 'Вашингтон' 'Барселона' 'Париж' 'Минск' 'Лондон' 'Вашингтон'
  'Токио' 'Токио' 'Вашингтон' 'Минск' 'Лондон' 'Минск' 'Токио' 'Пекин'
  'Берлин' 'Токио' 'Минск' 'Берлин' 'Вашингтон' 'Лондон' 'Вашингтон'
  'Барселона' 'Берлин' 'Токио' 'Пекин' 'Минск' 'Берлин' 'Москва' 'Париж'
  'Берлин' 'Токио' 'Минск' 'Нью-Йорк' 'Париж']]


7.Используя как можно меньше операций в исходном массиве "шахматная доска" np.zeros((8,8)) добиться расставки кодов "шахматных фигур".

In [ ]:
a7 = np.zeros((8,8))
a7[:2] = [[-4., -3., -2., -6., -5., -2., -3., -4.], [-1., -1., -1., -1., -1., -1., -1., -1.]]
a7[6:] = [ [1., 1., 1., 1., 1., 1., 1., 1.], [4., 3., 2., 6., 5., 2., 3., 4.]]
print(a7)

[[-4. -3. -2. -6. -5. -2. -3. -4.]
 [-1. -1. -1. -1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 4.  3.  2.  6.  5.  2.  3.  4.]]


8.Создать двухмерный массив 20 на 3, содержащийслучайные целые числа от 0 до 100. Интерпретируя массив как 20 векторов из 3х компонент, отсортировать массив по длине векторов.

In [ ]:
a8 = np.random.randint(0, 100, (20, 3))
b8 = np.sort(a8, axis = 1)
print(b8)

[[ 9 47 63]
 [ 6 49 63]
 [39 50 86]
 [16 36 73]
 [ 5 59 83]
 [ 0 66 82]
 [18 24 77]
 [13 48 75]
 [ 6 36 45]
 [50 60 79]
 [ 3  4 90]
 [39 49 71]
 [ 7 25 91]
 [ 4 10 65]
 [75 85 89]
 [16 26 73]
 [20 42 86]
 [ 4 57 61]
 [36 54 74]
 [ 7 45 53]]


9.Создать в numpy матрицу 11 на 7 вида: [[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]. При решении задачи применить технику распространения.

In [ ]:
a9 = [1, 2, 3, 4, 5, 6, 7]
b9 = [[0], [10], [20], [30], [40], [50], [60], [70], [80], [90], [100]]
c9 = [i[0] + i[1] for i in list(np.broadcast(a9, b9))]
print(np.array(c9).reshape(len(b9), 7))

[[  1   2   3   4   5   6   7]
 [ 11  12  13  14  15  16  17]
 [ 21  22  23  24  25  26  27]
 [ 31  32  33  34  35  36  37]
 [ 41  42  43  44  45  46  47]
 [ 51  52  53  54  55  56  57]
 [ 61  62  63  64  65  66  67]
 [ 71  72  73  74  75  76  77]
 [ 81  82  83  84  85  86  87]
 [ 91  92  93  94  95  96  97]
 [101 102 103 104 105 106 107]]


10.Создать массив из 20 случайных целых чисел от 0 до 100. Получить второе сверху значение в массиве. Опредлить индекс этого значения.

In [ ]:
a10 = np.random.randint(0, 101, 20)
b10 = np.setdiff1d(a10, a10.max())
print(b10.max())

87


11.Задан произвольный массив numpy (например массив из 100 случайных числе от 0 до 1). Необходимо найти в нем число наиболее близкое к заданному.

In [ ]:
a11 = np.random.random(100)
x = float(input('Введите значение: '))
print(a11[np.absolute(a11-x).argmin()])

Введите значение: 0.9
0.9056904465409032


12.Задать два двухмерных массива ar1 и ar2 размерности (4, 7), состоящих из случайных целых чисел в пределах от 0 до 10. Построить двухмерный массив размерности (4, 7), каждый элемент которого представляет собой максиум из двух значений, находящихся на аналогичной позиции в массивах ar1, ar2.

In [ ]:
ar1 = np.random.randint(0, 10, (4, 7))
ar2 = np.random.randint(0, 10, (4, 7))
print(np.maximum(ar1, ar2))

[[7 6 9 1 5 8 8]
 [6 7 5 4 8 4 5]
 [4 1 7 4 9 7 6]
 [9 8 4 7 7 9 8]]
